// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // ✅ Updated with your NEW Firebase Project Data (bgmiuc-74295)
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN_q_BcUTvSXkILqKIvO_FhYJ4jHSC-HY',
    appId: '1:225862888805:android:22311a25c8512dd56f058c', // Used the ID for com.sell
    messagingSenderId: '225862888805',
    projectId: 'bgmiuc-74295',
    storageBucket: 'bgmiuc-74295.firebasestorage.app',
  );

  // Note: iOS data kept from previous file as it wasn't in your new JSON. 
  // If you need to build for iOS later, run: flutterfire configure
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSmUcRo7dTnvFvPtUsZWGr_qbszANhtWA',
    appId: '1:705724924854:ios:a4d5856f75e2f6ccc4b717',
    messagingSenderId: '705724924854',
    projectId: 'contacts-app-b5a05',
    storageBucket: 'contacts-app-b5a05.appspot.com',
    androidClientId: '705724924854-r3b0ntdh2fi13v9psgc8dgl9ds4hf4nl.apps.googleusercontent.com',
    iosClientId: '705724924854-tvhiprg0kg1lvc77j8l8r3d8rr5va3bm.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );
}
