name: Build Flutter APK

on:
  push:
    branches:
      - main   # Trigger the action on the 'main' branch (change if you're using a different branch)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter (latest stable version)
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'   # 'stable' will automatically use the latest Flutter version

    - name: Install dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release

    - name: Upload APK to GitHub releases
      uses: softprops/action-gh-release@v1
      with:
        files: build/app/outputs/flutter-apk/app-release.apk

    - name: Clean up
      run: flutter clean